# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-26 12:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Baslik bilgisi burada girilir', max_length=100, verbose_name='Baslik Giriniz')),
                ('content', ckeditor.fields.RichTextField(max_length=5000, null=True, verbose_name='İcerik')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('unique_id', models.CharField(editable=False, max_length=100, null=True)),
                ('creating_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gonderiler',
                'ordering': ['-id'],
            },
        ),
    ]
