# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-27 17:17
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200626_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Kapak Fotosu Yukleyiniz', null=True, upload_to=blog.models.upload_to, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=1000, null=True, verbose_name='İcerik'),
        ),
    ]
