# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-30 11:57
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200630_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDizi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Baslik bilgisi burada girilir', max_length=100, verbose_name='Baslik Giriniz')),
                ('content', models.TextField(max_length=1000, null=True, verbose_name='İcerik')),
                ('image', models.ImageField(blank=True, default='default/ohdintropng.png', help_text='Kapak Fotosu Yukleyiniz', null=True, upload_to=blog.models.upload_to, verbose_name='Foto')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('creating_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'GonderilerDizi',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Baslik bilgisi burada girilir', max_length=100, verbose_name='Baslik Giriniz')),
                ('content', models.TextField(max_length=1000, null=True, verbose_name='İcerik')),
                ('image', models.ImageField(blank=True, default='default/ohdintropng.png', help_text='Kapak Fotosu Yukleyiniz', null=True, upload_to=blog.models.upload_to, verbose_name='Foto')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('creating_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'GonderilerFilm',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='bloggezi',
            options={'ordering': ['-id'], 'verbose_name_plural': 'GonderilerGezi'},
        ),
    ]
