# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-07-01 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200630_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdizi',
            name='unique_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogfilm',
            name='unique_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloggezi',
            name='unique_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
