# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-07-17 17:05
from __future__ import unicode_literals

import blog.models
import cropduster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogimagesgezi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimagesgezi',
            name='bloggezi',
        ),
        migrations.AlterField(
            model_name='bloggezi',
            name='image',
            field=cropduster.fields.CropDusterImageField(blank=True, db_column='image', default='', upload_to=blog.models.upload_to),
        ),
        migrations.DeleteModel(
            name='BlogImagesGezi',
        ),
    ]
