# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-07-17 17:45
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200717_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='bloggezi',
            name='image',
            field=models.ImageField(blank=True, default='default/ohdintropng.png', help_text='Kapak Fotosu Yukleyiniz', null=True, upload_to=blog.models.upload_to, verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogGezi'),
        ),
    ]
