# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-07-20 06:47
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200720_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesBlogGezi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.upload_to)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogGezi')),
            ],
        ),
    ]
