# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-07-20 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_imagesbloggezi'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesbloggezi',
            name='unique_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
