# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-07-20 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_imagesbloggezi_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesbloggezi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/media'),
        ),
    ]
