# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-07-20 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200720_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesbloggezi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog'),
        ),
    ]
