# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-07-20 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200720_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesbloggezi',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog'),
        ),
        migrations.AddField(
            model_name='imagesbloggezi',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog'),
        ),
        migrations.AddField(
            model_name='imagesbloggezi',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog'),
        ),
        migrations.AddField(
            model_name='imagesbloggezi',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog'),
        ),
    ]
