# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-07-20 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200720_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesbloggezi',
            options={'verbose_name_plural': 'ImagesGonderilerGezi'},
        ),
    ]
