# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-07-20 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200720_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesbloggezi',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='imagesbloggezi',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='imagesbloggezi',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='imagesbloggezi',
            name='image5',
        ),
        migrations.AlterField(
            model_name='bloggezi',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagesbloggezi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
