# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-09-06 10:11
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_imagesblogdizi_imagesblogfilm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Baslik bilgisi burada girilir', max_length=100, verbose_name='Baslik Giriniz')),
                ('content', models.TextField(max_length=1000, null=True, verbose_name='İcerik')),
                ('image', models.ImageField(blank=True, default='default/ohdintropng.png', help_text='Kapak Fotosu Yukleyiniz', null=True, upload_to=blog.models.upload_to, verbose_name='Foto')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('unique_id', models.CharField(editable=False, max_length=100, null=True)),
                ('creating_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'GonderilerHayat',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ImagesBlogHayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('unique_id', models.CharField(editable=False, max_length=100, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogHayat')),
            ],
            options={
                'verbose_name_plural': 'ImagesGonderilerHayat',
            },
        ),
    ]
