# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-09-14 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_bloghayat_imagesbloghayat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdizi',
            name='content',
            field=models.TextField(max_length=2500, null=True, verbose_name='İcerik'),
        ),
        migrations.AlterField(
            model_name='blogfilm',
            name='content',
            field=models.TextField(max_length=2500, null=True, verbose_name='İcerik'),
        ),
        migrations.AlterField(
            model_name='bloggezi',
            name='content',
            field=models.TextField(max_length=2500, null=True, verbose_name='İcerik'),
        ),
        migrations.AlterField(
            model_name='bloghayat',
            name='content',
            field=models.TextField(max_length=2500, null=True, verbose_name='İcerik'),
        ),
    ]
